sudo: required
language: objective-c
osx_image: xcode11.2
branches:
  only:
    - master
cache:
  timeout: 86400
  directories:
    - $HOME/unity_download_cache/ #Cache unity installer files
before_install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/coryleach/UnityTravisCI/master/bin/before-install.sh)
install:
  - source ./install.sh
script:
  - source ./auth.sh
  - source ./run-tests.sh
  - source ./deauth.sh
